[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Fuzzy = "a9166f1b-85e5-4df0-9c26-e06b441f12e8"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
